<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3_准备_js中的error</title>
</head>

<body>
    <!-- 
    进一步理解JS中的错误(Error)和错误处理
    mdn文档: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error

			1. 错误的类型
						Error: 所有错误的父类型
						ReferenceError: 引用的变量不存在
						TypeError: 数据类型不正确
						RangeError: 数据值不在其所允许的范围内--死循环
						SyntaxError: 语法错误
			2. 错误处理
						捕获错误: try{}catch(){}
						抛出错误: throw error
			3. 错误对象
						message属性: 错误相关信息
						stack属性: 记录信息
  -->

    <script type="text/javascript">
        //演示：ReferenceError: 引用的变量不存在
        /* console.log(a); */

        // 演示：TypeError: 数据类型不正确
        /* const demo = () => {}
        demo()() */

        // 演示：RangeError: 数据值不在其所允许的范围内--死循环
        /* const demo = () => {
            demo()
        }
        demo() */

        // 演示：SyntaxError: 语法错误(缺胳膊少腿)
        /* console.log(1; */

        // 如何捕获错误
        // try中放可能出现错误的代码，一旦出现错误，立即停止try中代码的执行，然后调用catch，并携带错误信息
        /* try {
            console.log(1);
            console.log(a);
            console.log(2);
        } catch (error) {
            console.log('代码执行出错了，错误的原因是：', error);
        } */

        // 如何抛出一个错误
        function demo() {
            const date = Date.now()
            if (date % 2 === 0) {
                console.log("偶数，可以正常工作");
            } else {
                throw new Error('奇数，不可以正常工作')
            }
        }
        try {
            demo()
        } catch (error) {
            debugger;
            console.log('@', error);
        }
    </script>

</body>

</html>